### ISSUE TITLE
`XTranslateCoordinates` or related crash

### ISSUE THREAD

**Issue by mhsjlw** [mhsjlw/mcpilauncher#3]
It likely crashes at `XTranslateCoordinates`, or some function accessing the struct fields of [XGetWindowAttributes](https://www.x.org/releases/X11R7.7/doc/man/man3/XGetWindowAttributes.3.xhtml)

Here's the program output:

```
x_unlock_function()
XGetWindowAttributes(window = 0)
XTranslateCoordinates(window = 0)
// x_lock_function() should be called
```

The code that handles the `X`-related functions: 

```c
int XTranslateCoordinates(Display *display, Window src_w, Window dest_w, int src_x, int src_y, int *dest_x_return, int *dest_y_return, Window *child_return) {
  printf("XTranslateCoordinates(window = %d)\n", src_w);

  *dest_x_return = 0;
  *dest_y_return = 0;
  *child_return = 0;

  return 1;
}

int XGetWindowAttributes(Display *display, Window w, XWindowAttributes *window_attributes_return) {
  printf("XGetWindowAttributes(window = %d)\n", w);

  memset(window_attributes_return, 0, sizeof(XWindowAttributes));

  window_attributes_return->visual = 0xdeadbeef;
  window_attributes_return->screen = 0xdeadbeef;

  return 1;
}
```

Something is going wrong with how the structs are handled/used/generated, not sure how to debug this one to figure it out.

**Comment by JayFoxRox** [comment]
You should document why this issue was closed, just in case you (or others) run into this (or similar issues) in the future.

**Comment by mhsjlw** [comment]
Outlined in https://github.com/mhsjlw/mcpilauncher/commit/356004521cf846985be3dd810de19e5a2a1bf717 -- forgot to add it here
